use bitcoin::BlockHash;
use bitcoincore_rpc::{Auth, Client, RpcApi};
// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{BLOCK_GUEST_ELF, BLOCK_GUEST_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let input = {
        let mut input = Vec::new();
        let url = "http://127.0.0.1:18443";
        let auth = Auth::UserPass("admin1".into(), "123".into());

        let client = Client::new(url, auth).unwrap();

        let begin = 10;
        let end = 20;
        for i in begin..=end {
            let hash = client.get_block_hash(i).unwrap();
            let header = client.get_block_header(&hash).unwrap();
            input.push((i, header));
        }
        input
    };

    let env = ExecutorEnv::builder()
        .write(&input)
        .unwrap()
        .build()
        .unwrap();

    let prover = default_prover();

    let receipt = prover.prove(env, BLOCK_GUEST_ELF).unwrap();

    let output: (u64, BlockHash) = receipt.journal.decode().unwrap();
    println!("output:{:?}", output);

    receipt.verify(BLOCK_GUEST_ID).unwrap();
}
